name: app

type: php:8.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

variables:
    env:
        DATABASE_URL: "mysql://Adrien:Studi.1$@127.0.0.1:3306/ZooArcadia?serverVersion=8.0&charset=utf8mb4"

build:
    flavor: none

disk: 1024

relationships:
    database: "mysql:mysql"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

workers:
    messenger:
        size: XS
        resources:
            base_memory: 64
            memory_ratio: 128
        commands:
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e
        symfony-deploy

